---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args:
          - --output-format=full
        exclude: ^source/tools/webservices/
      - id: ruff-format
        args:
          - --check
          - --target-version
          - py311
        exclude: ^source/tools/webservices/
