# default excludes minus "dist"
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "node_modules",
    "venv"]

line-length = 99

target-version = "py311"

[format]
line-ending = "lf"

[lint]
select = ["ALL"]
ignore = [
    "ANN",
    "C90",
    "COM812",
    "D10",
    "EM",
    "FIX002",
    "FBT",
    "PERF401",
    "PLR0912",
    "PLR0915",
    "PLR2004",
    "PLW2901",
    "PT",
    "PTH",
    "S101",
    "S314",
    "S603",
    "S607",
    "T20",
    "TD002",
    "TD003",
    "TRY003",
    "W505"
]

[lint.isort]
lines-after-imports = 2

[lint.pycodestyle]
max-doc-length = 72

[lint.pydocstyle]
convention = "pep257"

[lint.pylint]
max-args = 8
