---
# yamllint disable rule:line-length
name: lint
on:
  - pull_request
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    env:
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
    steps:
      - uses: actions/checkout@v4

      # cache only works for items in workspace, so configure apt to allow for caching.
      - name: Setup apt cache locations
        id: apt-cache-location
        run: |
          mkdir -p apt-cache/archives/partial
          mkdir -p apt-lists/partial
          mkdir -p apt-lists/auxfiles
          sudo echo "Dir::Cache \"$(realpath apt-cache)\";" >/etc/apt/apt.conf.d/99cachelocation
          sudo echo "Dir::State::lists \"$(realpath apt-lists)\";" >>/etc/apt/apt.conf.d/99cachelocation

      - name: Cache apt pkg db and and deb files
        id: apt-cache
        uses: actions/cache@v4
        with:
          path: |
            apt-cache
            apt-lists
          key: ${{ runner.os }}-apt-cache-4

      - name: Update package db
        if: steps.apt-cache.outputs.cache-hit != 'true'
        run: sudo apt-get update

      - name: Install cppcheck
        run: sudo apt-get --assume-yes --no-install-recommends install cppcheck

      - name: Fetch the base branch, so we can use `git diff`
        run: git fetch origin ${{ env.BASE_SHA }}

      - name: Check for issues
        run: ./source/tools/lint/cppcheck/cppcheck.sh --diff ${{ env.BASE_SHA }}
