---
blank_issues_enabled: false
contact_links:
  - name: Help & Feedback
    url: https://wildfiregames.com/forum/forum/145-help-amp-feedback/
    about: >
      If you need help or have feedback, please open a thread in the forums.
